### ISSUE TITLE
Error TypeError: runner.metro.getBundler... when trying to run the project.

### ISSUE THREAD

**Issue by carl0smat3us** [kurogai/hinode#7]
I'm currently encountering an issue when attempting to run my project using the following command:

```shell
yarn run start
```

I receive the following error in the console:

<pre><font color="#A2734C">Development build: Unable to get the default URI scheme for the project. Please make sure the expo-dev-client package is installed.</font>
<font color="#5E5C64">Starting project at /home/carl0smat3us/Documentos/hinode</font>
<font color="#A2734C"><b>● Validation Warning</b></font><font color="#A2734C">:</font>

<font color="#A2734C">  Unknown option </font><font color="#A2734C"><b>&quot;watcher&quot;</b></font><font color="#A2734C"> with value </font><font color="#A2734C"><b>{&quot;additionalExts&quot;: [&quot;env.development.local&quot;, &quot;env.local&quot;, &quot;env.development&quot;, &quot;env&quot;]}</b></font><font color="#A2734C"> was found.</font>
<font color="#A2734C">  This is probably a typing mistake. Fixing it will remove this message.</font>

Starting Metro Bundler
<font color="#C01C28">TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function</font>
<font color="#5E5C64">TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function</font>
<font color="#5E5C64">    at Object.observeFileChanges (/home/carl0smat3us/Documentos/hinode/node_modules/@expo/cli/build/src/start/server/metro/waitForMetroToObserveTypeScriptFile.js:44:60)</font>
<font color="#5E5C64">    at MetroBundlerDevServer.watchEnvironmentVariables (/home/carl0smat3us/Documentos/hinode/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js:209:51)</font>
<font color="#5E5C64">    at DevServerManager.watchEnvironmentVariables (/home/carl0smat3us/Documentos/hinode/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:192:35)</font>
<font color="#5E5C64">    at startAsync (/home/carl0smat3us/Documentos/hinode/node_modules/@expo/cli/build/src/start/startAsync.js:127:32)</font>
<font color="#C01C28">error</font> Command failed with exit code 1.
<font color="#12488B">info</font> Visit <b>https://yarnpkg.com/en/docs/cli/run</b> for documentation about this command.
</pre>

Configuration Information:

Operating System: Ubuntu 22.04.3 LTS x86_64
Node.js Version: v18.17.1
Yarn Version: 1.22.19

**Comment by kurogai** [comment]
I need to update this repo since synk changed some package versions, thanks for the information provided

**Comment by lucas-cota** [comment]
> I need to update this repository since synk changed some versions of the package, thanks for the info provided

I have an application with the Expo and also with the same problem, how did you manage to solve it?
